### ISSUE TITLE
add option to disable keep_trailing_newline

### ISSUE THREAD

**Issue by AlJohri** [kblomqvist/yasha#13]
http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control

Jinja strips trailing new lines by default. It would be great to have an option to keep them.

**Comment by AlJohri** [comment]
replaced by #14

**Comment by AlJohri** [comment]
@kblomqvist can you push out a new version with this change?

**Comment by kblomqvist** [comment]
I would like to finalize #11 before making new release.

**Comment by kblomqvist** [comment]
I made a new release. For now make sure that you use `-V` for variable file. `-v` was given for "inline variables" given directly via command-line.

https://github.com/kblomqvist/yasha/releases/tag/3.0
