### ISSUE TITLE
SCons builder broken since v3.0

### ISSUE THREAD

**Issue by kblomqvist** [kblomqvist/yasha#22]
The builder still uses `-e` and `-v` to detect extension/variable file. Maybe `-d`, _"define"_, would have been better for inline variables.

Revert `-V` and `-E` back to small letters?

**Comment by dfee** [comment]
Just my 2¢ – since you're already using Click, you could [forward unknown options](http://click.pocoo.org/5/advanced/#forwarding-unknown-options), e.g. `--my_var 123`. That might be a cleaner syntax and avoid the ambiguous `-v` / `-V` situation.

**Comment by kblomqvist** [comment]
Interesting idea. I will try to play with it.

**Comment by kblomqvist** [comment]
```
--foo bar
--foo=bar
--foo=bar,baz
```
The list like variable is converted to a list, i.e. `foo = ['bar', 'baz']`.

**Comment by kblomqvist** [comment]
Do you think that we should remove long names from `-v` and `-e` to not reserve those keywords being used as an inline variable?

**Comment by dfee** [comment]
Great question. I don't have a position on that.

**Comment by kblomqvist** [comment]
I will leave the long option names as is. How should we call the unknown options, i.e. variables given via command-line. I have called them as "inline variables". Is that even a correct name?

The improved help would look like this:
```
Usage: yasha [OPTIONS] [INLINE_VARIABLES]... TEMPLATE

  Reads the given Jinja TEMPLATE and renders its content into a new file.
  For example, a template called 'foo.c.j2' will be written into 'foo.c' in
  case the output file name is not explicitly given. Unknown options are
  considered as template variables, e.g.

      yasha --hello=world -o hello.txt hello.j2

  defines a variable 'hello' for a template like:

      Hello {{ hello }}!

  producing:

      Hello world!

Options:
  -o, --output FILENAME         Place the rendered template into FILENAME.
  -v, --variables FILENAME      Read template variables from FILENAME. Builtin
                                parsers: JSON, TOML and YAML.
  -e, --extension FILENAME      Read template extensions from FILENAME. A
                                Python file is expected.
  -I, --include_path DIRECTORY  Add DIRECTORY to the list of directories to be
                                searched for the referenced templates, i.e.
                                files imported via 'include', 'extends' and
                                'import' statementss
  --no-variables                Omit template variable file.
  --no-extensions               Omit template extension file.
  --no-trim-blocks              Load Jinja with trim_blocks=False.
  --no-lstrip-blocks            Load Jinja with lstrip_blocks=False.
  --keep-trailing-newline       Load Jinja with keep_trailing_newline=True.
  -M                            Outputs Makefile compatible list of
                                dependencies. Doesn't render the template.
  -MD                           Creates Makefile compatible .d file alongside
                                the rendered template.
  --version                     Print version and exit.
  -h, --help                    Show this message and exit.
```

**Comment by dfee** [comment]
I think your options for long option names are:
1. no namespace: the user needs to be aware of the yasha namespace (e.g. --no-variables)
2. namespace: the user would prefix with --x-{my-var-name} (collisions aren't possible). would likely require parsing to turn `--x-my-opt` -> `x_my_opt` (provided by click) -> `my_opt` provided by yasha
3. use a prefix like `-v` (currently used for variable file) or `-e` (currently used for extension) to avoid namespacing issues. (`-v` could become `-c`, `--config`).

I'm really not sure what the best approach forward is here. It's a matter of taste I guess, but I'd probably lean towards \#2 or \#3.

**Comment by kblomqvist** [comment]
Well I kind of decided to reserve, `output`, `variables`, `extensions` and `include_path` keywords. So those cannot be used to define variable via command-line.

`--no-variables` and `-no-extensions` are to disable their respective file lookup. I could be more specific and change those to `--no-variable-file` and `--no-extension-file`.

What I was after was that should we call the unknown long options, which you may define via command-line, to something else than `INLINE_VARIABLES`. Maybe `CLI_VARIABLES`? I think that the main use case is to overwrite a variable defined in a file.

**Comment by dfee** [comment]
How about `TEMPLATE_VARIABLES`?

**Comment by kblomqvist** [comment]
I also decided to pass the variable to `ast.literal_eval()` to support Python literal or container kind of inputs:

```
yasha --var=1 template.j2  # type(var) == int
yasha --hello="('foo','bar')" -o- hello.j2  # type(var) == tuple
yasha --var="{'muffin':'lolz','foo': 'kitty'}" template.j2  # type(var) == dict
```
