### ISSUE TITLE
Multiple variable files?

### ISSUE THREAD

**Issue by jpotter** [kblomqvist/yasha#38]
Hi Kim -- thanks for open-sourcing Yasha, I've been playing with it for part of our build system and find it does a lot of what we need easily.

However, I'm needing to pass two variable files in -- one variable file that's build settings (we build our site for production with different google analytics tag, for example), and then the second variable file that's the data for the specific page (i.e. the .yaml file that's auto-discovered as having the same name as the .j2 file).

Looking at the code, cli.py line 223 could take an array of variable files -- but the logic would need minor adjustments on the flags coming in. (Because the --variables flag overrides the auto-discovery logic, and not wanting to break any existing scripts that use that, might need an --additional-variables type flag?).

Do you see a way of doing this otherwise than as I'm suggesting? ...if I submitted a pull request that did this, would you be open to including it?

Thanks!
-Jeff

**Comment by kblomqvist** [comment]
Hi Jeff. I think this should be possible via click's multiple options. Additionally, in case the variable file is given (one or multiple) auto-discovery should not be used. I'm happy to accept PR using this approach, see http://click.pocoo.org/5/options/#multiple-options.

```
yasha -v varfile1.yaml -v varfile2.yaml template.j2
```

**Comment by jpotter** [comment]
Thanks, Kim -- I submitted a pull request. I'm not sure I understand why it failed the travis build though? I'll close this issue out and we can carry on under the pull request. :)
