### ISSUE TITLE
Raise an error if variable is not present in the template

### ISSUE THREAD

**Issue by pcsegal** [kblomqvist/yasha#42]
Is there a way that I can run yasha so that it raises an error if a variable is present in the template but is not passed as a variable?

Thank you in advance.

**Comment by kblomqvist** [comment]
This would need Jinja to be loaded with `undefined=jinja2.StrictUndefined`. So to support this a new cli option should be introduced, e.g.

```bash
echo "{{var}}" | yasha --strict -
jinja2.exceptions.UndefinedError: 'var' is undefined
```

**Comment by kblomqvist** [comment]
Can you test if the new ``--pedantic`` option works for you?

**Comment by pcsegal** [comment]
Yes, just tested it and seems to work very well. Thank you!

**Comment by kblomqvist** [comment]
I have changed `--pedantic` to `--mode` to also support Jinja's `DebugUndefined`. See #44.
