### ISSUE TITLE
How to override Jinja2 block_start_string

### ISSUE THREAD

**Issue by elgalu** [kblomqvist/yasha#43]
Hi, I'm trying to override certain Jinja2 environment defaults like `block_start_string`:

```py
import jinja2

jinja_env = jinja2.Environment(
    block_start_string = '<%',
    block_end_string = '%>',
    variable_start_string = '<<',
    variable_end_string = '>>'
)
```

I'm loading that extension file with `yasha -e my_extension.py` however it doesn't take effect as I don't know how to activate that `jinja_env` I'm creating.

Thanks for maintaining this project!

**Comment by kblomqvist** [comment]
Unfortunately that's not possible. Yasha's file extensions support only `jinja2.ext` classes, not `jinja2.Environment`. However, I would like to support Environments too as I have had plans to use Yasha for Latex, see #31 and #33.

**Comment by elgalu** [comment]
Thanks for the prompt response @kblomqvist and very glad to read its on your plans:)

**Comment by elgalu** [comment]
Can you point me where in there source could I hard-code this settings? until is done "properly" ?

**Comment by kblomqvist** [comment]
https://github.com/kblomqvist/yasha/blob/master/yasha/yasha.py#L127

**Comment by kblomqvist** [comment]
A note to myself. [Jinja's defaults](https://github.com/pallets/jinja/blob/master/jinja2/defaults.py) could be overridden by local keys defined in Yasha's file extensions.

```python
# extension.py
BLOCK_START_STRING = '{%'
BLOCK_END_STRING = '%}'
VARIABLE_START_STRING = '{{'
VARIABLE_END_STRING = '}}'
COMMENT_START_STRING = '{#'
COMMENT_END_STRING = '#}'
LINE_STATEMENT_PREFIX = None
LINE_COMMENT_PREFIX = None
TRIM_BLOCKS = False
LSTRIP_BLOCKS = False
NEWLINE_SEQUENCE = '\n'
KEEP_TRAILING_NEWLINE = False
```

**Comment by elgalu** [comment]
Works!! Thanks
