### ISSUE TITLE
Is it possible to avoid exception in case a variable cannot be resolved in template

### ISSUE THREAD

**Issue by ghilainm** [kblomqvist/yasha#44]
I would like to replace variables in a template file but some may not be defined and in that case I would like the variables to stay in the generated file. Is it possible?

**Comment by kblomqvist** [comment]
I'm not sure what you are trying to achieve. Would you like to use [Jinja's debug](http://jinja.pocoo.org/docs/2.10/api/#jinja2.DebugUndefined) for undefined variables, or something like this:

```jinja2
{{ "foo" if not foo else foo }}
```

**Comment by kblomqvist** [comment]
Ok. In that case you would like to use Jinja's debug. For now, it is not possible. I could add a command-line option to support that though, i.e. `--jinja-debug`.

**Comment by ghilainm** [comment]
That would be nice I think. You can also document the use case as it is not obvious that --jinja-debug has this effect. Maybe just a link to the jinja-debug documentation is enough.
