### ISSUE TITLE
use jinja2 extension

### ISSUE THREAD

**Issue by dragouf** [kblomqvist/yasha#49]
I would like to use jinja2.ext.do but I can't find how to use it. -e parameter expect a filename and I don't know what to write for that.

**Comment by kblomqvist** [comment]
Unfortunately `-e` does not (yet) support the loading of Python modules. For now, it can only support file extensions, i.e., you need to write a Python file where to put your extensions.

To get `do` to work in your templates you could try the following

```bash
echo "from jinja2.ext import do" > do.py
yasha -e do.py -v variables.yaml template.j2
```
