### ISSUE TITLE
Extensions are not loaded completely into the Jinja Environment

### ISSUE THREAD

**Issue by mobious01** [kblomqvist/yasha#52]
The classes inspected through the extensions file are correctly added to the `classes` list. However the module member `CLASSES` which is the object passed to `yasha.load_jinja` is not updated with it. The code below may be needed for the extension classes to reflect all the way to the Jinja environment.

```
#yasha/cli.py
def load_extensions(file):
#...
try:
    CLASSES.update(module.CLASSES)
except AttributeError:
    CLASSES.update(classes)
```

**Comment by kblomqvist** [comment]
You're correct. I'll fix it with unit tests. Thanks for reporting.
