### ISSUE TITLE
passing string with commas as parameter

### ISSUE THREAD

**Issue by nikolaevn** [kblomqvist/yasha#57]
Is there a way to pass a string like 'a,b,c' as cli parameter that would be interpreped as string, not as list?
According to yasha.py it will be converted to list anyway
```
...
 if isinstance(val, str) and ',' in val:
            # Convert foo,bar,baz to list ['foo', 'bar', 'baz']
            val = val.split(',')
variables[opt] = val
...
```

**Comment by kblomqvist** [comment]
Hmm.. can you try `--mystring '"a,b,c"'`

**Comment by nikolaevn** [comment]
> 
> 
> Hmm.. can you try `--mystring '"a,b,c"'`

Have tried it - without success.
I use yasha version 4.3 with python 3.7.1
